use master
go
CREATE DATABASE SHOPPE
GO
DROP DATABASE SHOPPE
USE SHOPPE
GO
CREATE TABLE [USER]
(
    GMAIL        VARCHAR(225) PRIMARY KEY NOT NULL,
    PASSWORD     VARCHAR(225)             NOT NULL,
    USERNAME     NVARCHAR(100)            NOT NULL,
    PHONE_NUMBER VARCHAR(13)              NOT NULL,
    ADDRESS      NVARCHAR(225)            NOT NULL,
)
GO
CREATE TABLE ROLE
(
    ROLE_ID   INT IDENTITY (1,1) PRIMARY KEY,
    ROLE_NAME NVARCHAR(30)
)
GO
CREATE TABLE ACCOUNT
(
    ACCOUNT_ID INT IDENTITY (1,1) PRIMARY KEY,
    GMAIL      VARCHAR(225) FOREIGN KEY REFERENCES ACCOUNT (GMAIL),
    NICK_NAME  VARCHAR(100)   NOT NULL,
    AVATAR     VARBINARY(MAX) NOT NULL,
    OTHER_INFO NVARCHAR(300),
    ROLE_ID    INT FOREIGN KEY REFERENCES ROLE (ROLE_ID)
)
GO
CREATE TABLE TYPES
(
    TYPES_ID   INT IDENTITY (1,1) PRIMARY KEY,
    TYPES_NAME NVARCHAR(100) NOT NULL
)
GO
CREATE TABLE PRODUCT
(
    PRODUCT_ID          INT IDENTITY (1,1) PRIMARY KEY,
    PRODUCT_NAME        NVARCHAR(255)  NOT NULL,
    PRODUCT_DESCRIPTION NVARCHAR(200),
    PRODUCT_IMAGE       VARBINARY(MAX),
    PRODUCT_COLOR       VARBINARY(100) NOT NULL,
    PRODUCT_ORIGIN      NVARCHAR(50),
    PRODUCT_PRICE       FLOAT CHECK (PRODUCT_PRICE >= 0)
)
GO
CREATE TABLE PRODUCT_TYPE
(
    PRODUCT_ID   INT FOREIGN KEY REFERENCES PRODUCT (PRODUCT_ID),
    TYPE_ID      INT FOREIGN KEY REFERENCES TYPES (TYPES_ID),
    TYPE_DETAILS NVARCHAR(100),
    TYPE_NAME    NVARCHAR(100)
)
GO
CREATE TABLE WAREHOUSE
(
    WAREHOUSE_ID     INT IDENTITY (1,1) PRIMARY KEY,
    PRODUCT_ID       INT FOREIGN KEY REFERENCES PRODUCT (PRODUCT_ID),
    PRODUCT_QUANTITY INT CHECK (PRODUCT_QUANTITY > 0)
)
GO
CREATE TABLE WAREHOUSE_PRODUCT
(
    WAREHOUSE_ID INT FOREIGN KEY REFERENCES WAREHOUSE (WAREHOUSE_ID),
    PRODUCT_ID   INT FOREIGN KEY REFERENCES PRODUCT (PRODUCT_ID)
)
GO
CREATE TABLE SHOP
(
    SHOP_ID          INT IDENTITY (1,1) PRIMARY KEY,
    SHOP_NAME        NVARCHAR(255)  NOT NULL,
    SHOP_IMAGE       VARBINARY(MAX) NOT NULL,
    SHOP_DESCRIPTION NVARCHAR(300),
    WAREHOUSE_ID     INT FOREIGN KEY REFERENCES WAREHOUSE (WAREHOUSE_ID)
)
GO
CREATE TABLE SHOP_WAREHOUSE
(
    SHOP_ID      INT FOREIGN KEY REFERENCES SHOP (SHOP_ID),
    WAREHOUSE_ID INT FOREIGN KEY REFERENCES WAREHOUSE (WAREHOUSE_ID)
)
GO
CREATE TABLE ORDER
(
    ORDER_ID          INT IDENTITY (1,1) PRIMARY KEY,
    PRODUCT_ID        INT FOREIGN KEY REFERENCES PRODUCT (PRODUCT_ID),
    SHOP_ID           INT FOREIGN KEY REFERENCES SHOP (SHOP_ID),
    ACCOUNT_ID        INT FOREIGN KEY REFERENCES ACCOUNT (ACCOUNT_ID),
    ORDER_DESCRIPTION NVARCHAR(300),
)
GO
CREATE TABLE ORDER_DETAILS
(
    ORDER_DETAILID INT IDENTITY (1,1) PRIMARY KEY,
    ORDER_ID       INT FOREIGN KEY REFERENCES ORDER (ORDER_ID),
    ORDER_STATUS   BIT,
)
GO
/*
CREATE TABLE COMMENT(
    COMMENT_ID INT IDENTITY (1,1) PRIMARY KEY ,
    COMMENT_CONTENT NVARCHAR(200),
    PRODUCT_ID INT FOREIGN KEY REFERENCES PRODUCT(PRODUCT_ID),
    ACCOUNT_ID INT FOREIGN KEY REFERENCES ACCOUNT(ACCOUNT_ID),
    COMMENT_DATE DATETIME,
)
GO
CREATE TABLE EMOJ(
    EMOJ_ID INT IDENTITY (1,1) PRIMARY KEY ,
    COMMENT_ID INT FOREIGN KEY REFERENCES COMMENT(COMMENT_ID),
    EMOJ_CONTENT NVARCHAR(10)
)*/
--- DOANH THU
---
--- CO THE COMENT DC NHIU SAN PHAM VA 1 SAN PHAM CMT NHIU LAN
--- CO THE THA CAM XUC CMT 1 LAN VA THA DC NHIU CMT

